### ISSUE TITLE
Breadcrumbs need a button to navigate to selected viewmodel

### ISSUE THREAD

**Issue by jaworekplay** [jaworekplay/WinFormsAndWPF#1]
CaptainCrewe!
Your task, should you accept it, is to fix breadcrumbs, so when user click on text of view models title it will take them to that VM. If you want to feel extra creative could you make the border on buttons for the breadcrumbs to disappear when mouse isn't over them or make a very gentle border and change it to whatever colour you think will look best. For extra points you can create an SSDT project that would contain our db.

Sincerely Mr Brightside

**Comment by CaptainCrewe** [comment]
Good morning Mr Brightside,

I'll be delighted to tackle this request, just not sure when.  I did manage to get the Push working from SourceTree - took a bit of looking around the account settings and then authorising my GitHub credentials with Atlassian.

I also took the opportunity to update my system installation of Git.

I do hope to get to this soon so that our beloved users can have an enhanced breadcrumb experience.

Yours in the ether,

CaptainCrewe
